[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "7156475fd5e5d77d5d0cb433bead177aa21e1900"
owners = [
    "imaginary-png",
]
project_path = "HuntHelper"
changelog = "first release"