[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "eec9b7e954d91b9a64606b9fb4df98c75950d1ee"
owners = [
    "imaginary-png",
]
project_path = "HuntHelper"
changelog = "first release"