[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "3ef731317c3fd675d8ec2f1b1f1ebefe81adb4fb"
owners = [
    "imaginary-png",
]
project_path = "HuntHelper"
changelog = ""