[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "1482e8e0c55d5b03705339e4f01edb6e37a51173"
owners = [
    "imaginary-png",
]
project_path = "HuntHelper"
changelog = ""