[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "13dbb49e2eccd38467dd55b8d291f3e3f598a9a7"
owners = [
    "imaginary-png",
]
project_path = "HuntHelper"
changelog = "Added Counters and Spawn point recording -- for S ranks"