[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "bfdce09cf36095b1c15974e65fc464dbd3b39afc"
owners = [
    "imaginary-png",
]
project_path = "HuntHelper"
changelog = ""