[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "ecf733f74f0e5f9a3e5fbb80489bc3a69856a89b"
owners = [
    "imaginary-png",
]
project_path = "HuntHelper"
changelog = "Added Counters and Spawn point recording -- for S ranks"