[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "a8d7af98c938f41157c75742b704f077422202c3"
owners = [
    "imaginary-png",
]
project_path = "HuntHelper"
changelog = "fixed scaling ? ; ;"